### ISSUE TITLE
RFC: PyLadies Global Governance Model

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/global-organizing#11]
## Overview

At PyCon USA 2019, several PyLadies organizers and other key stakeholders met to discuss the future of PyLadies (see [minutes](https://github.com/pyladies/global-organizing/blob/master/notes/2019/06_05_2019.md) and [slides](http://bit.ly/futurepyladies)). This meeting was called for several reasons including, but not limited to:

- Organizational priorities 
- Resource management
- Fundraising 

### Inspiration

Right now PyLadies is unable to engage the community in opportunities outside of being involved in their own direct chapter. PyLadies shared concerns have fallen on the shoulders of a select few (and has lead to very bad burn out) specifically because:

* We lack a structure to make decisions for non-chapter specific items
* Lack of expertise on working on the things that need to be worked on
* Lack of volunteers (with bandwidth) in general
* No obvious point of contact between PyLadies and the Python Software Foundation 

Let's look at some examples: 

1. Updating and maintaining pyladies.com and our `pip install pyladies`. 

*Problem:* There's lots of backed up PRs for the repo, for example reviewing and accepting blog posts has been virtually non-existent since 2016. There is no clear group to oversee the PyLadies shared technical resources. 

2. Code of Conduct reporting and mediation

*Problem:* We have had some Code of Conduct reports come in and without a clear group that can receive those reports we aren't able to do much. Also Code of Conduct work requires: training, expertise in enforcement policies, etc. We can't just have a broad community take this on as it can involve legal and safety issues.

3. PyLadies finances and fundraising for it. 

*Problem:* How can we allocate PyLadies funds (because yes we have some) to all our chapters? Right now there is no mechanism or body to dictate policy on this. And having an entire community execute this opens us up to inconsistency, lack of oversight, etc.

As the above examples show, most of this work is outside immediate PyLadies chapter management. 

### Future of Us PyCon USA 2019 Workshop Kickoff

After brainstorming with the Future of PyLadies members at PyCon the following themes emerged:

- Global Leadership (10 Votes)
- Finance / Funds (8 Votes)
- Resources (5 Votes)
- Support Network (3 Votes)
- Code of Conduct (2 Votes)
- Name and Branding (2 Votes)
- Tech (2 Votes)
- Connectedness (1 Votes)
- Decentral & Autonomy (0 Votes) - This is more of a description of our community & question if we should continue this way.

Overwhelmingly the workshop participants identified that absence of a global leadership structure as the highest priority for PyLadies to answer as we prepare for the future.

### R-Ladies Inspired Global Model: A Global Working Group with Project Based Pillars

When conducting research, @lorenanicole investigated a [few models including](https://docs.google.com/document/d/1IJlt8oSfXBeJzoGz_mNw9vlDi5PF4TkK-wb4724sEGM/edit?usp=sharing):

- R-Ladies
- Girl Develop It
- Women Who Code
- Django Girls
- Women in Machine Learning Data Science (WiMLDS)

Of these explored, we've settled on the R-Ladies model since there are several similarities between our two groups. Of primary importance, the R-Ladies model retains major decision making powers at the local chapter level for how that chapter functions day to day. PyLadies has historically been a decentralized organization, and we want to make sure we continue to promote that autonomy of individual chapters to work as they historically have. 

Another benefit of the R-Ladies model is that, like PyLadies, R-Ladies is a "choose your own commitment" model. Therefore if someone wants to be involved in something specific, such as tech, there is a project pillar to be involved in. We've selected our project pillars based on the initial themes voted on from the PyCon 2019 meeting (see above). If someone simply wants to provide feedback to a team for overarching concerns for all chapters, we have a Global team to consider and work on those concerns. 

We've refined the model to work with PyLadies and also to define how PyLadies will work with the Python Software Foundation:

![image](https://user-images.githubusercontent.com/4573607/62094877-3fd5b080-b244-11e9-822a-efce65767f6b.png)

Reference: [R-Ladies Structure](https://rladies.org/about-us/)

**PyLadies Global Leadership Team**
The size of the global team, who will be selected to be on the global team, length of tenure on the global team are all details that will be decided in a subsequent issue once the RFC for this model has closed. Additionally the Global leadership team itself is free to make adjustments to how this group functions.

An example of a primary concern for PyLadies Global will be to manage public assets for PyLadies and manage the relationship with the Python Software Foundation. Additionally the Global team will take on bigger initiatives such as global fundraising efforts.

**PyLadies Global Advisors Team**
This group will be invite only and include veteran organizers as well as those that previously have served on the PyLadies Global team. They will be available to consult the Global team as needed through such means as email, Slack, etc. 

**PyLadies Global and Python Software Foundation**
The PyLadies global leadership team will work directly with the Python Software Foundation. One or a few group members will be appointed the official point of contact to work with the Python Software Foundation. 

**Project Pillars**
From the PyLadies Future of Us workshop we will start with the following project pillars: Finance, Resources, Code of Conduct, Marketing and Branding, and Tech. Examples of other pillars that we may want to add in the future include a "PyLadies Conference" pillar should PyLadies wish to hold an international conference. Whatever additional pillars the community may want should be presented to the global group, highlighting the focus of the project, the project lead(s), and any other relevant information. 

Any PyLadies member will be eligible to be join a project team or to put their name forward to lead the project pillar. Project pillars can be run by 1+ members. On a structured basis the project teams will send reports to the Global leadership team. How frequently that communication will be and what that communication will look like is subject to how the initial Global leadership team decides is best.

In short, projects are meant to be flexible, be expanded upon or end, and open to the community to participate in. 

### Questions

- What is the formal relationship between the Python Software Foundation and PyLadies in this model?

See the above, but the Global leadership team will have some subset of it's members appointed to act as the official point of contact. 

- I don’t see a project pillar for a topic I want to work on! Can we add it?

The project pillars highlighted above are suggestions created from the PyCon US “Future of PYladies” discussion and are meant as suggestions of where to start. This model doesn’t mandate how many projects or what projects but instead proposes the use of project pillars to encourage a grassroots approach to PyLadies work. Members are free to suggest new ones and join only those they see fit. Some projects may always have work and others may be temporary. 

- Who are we selecting for the global team and how?

These are great questions but are outside the scope of this RFC. Once we have settled on a model and answered / addressed any concern of our governance model we can move to the next stage of answering these questions. 

- I want to work on making a PyLadies Conference. Where is that captured?

In 2015 a Pan Pacific PyLadies conference was suggested that lead to in 2016 the hope for a PyLadies conference. After two unsuccessful rounds of finding a location and conference chair, the entire idea crumbled. While many of us are interested in a PyLadies conference there are larger problems we saw that prevented a conference from moving past the ideation stage. These shortcomings arose in part from not having a clear group to work with to help manage projects that are global by nature. Learning from the past, the global interim team wants to help provide that structure to give global projects like a PyLadies Conference the tools and structural support needed to succeed. 

- What is expected to concretely change as a result of adopting a governance model?

We cover this in the "Overview" category above as:

- Organizational priorities
- Resource management
- Fundraising

However for very tangible examples we had added example problems in the "Inspiration" section. Other such examples include:

- No one clearly owns PyLades resources like our website, the pip install pyladies, the blog, etc. 
- No one clearly owns creating new PyLadies chapters
- We are unable to provide direct financial support to our PyLadies chapters
- We do not have a formally established relationship with the Python Software Foundation, whom is our parent org and gives us our non-profit status
- We do not have a team to handle global Code of Conduct concerns
- We do not have clear ways to allow PyLadies members to get involved in cross cutting concerns (e.g. organizing PyLadies at PyCon USA)
- PyLadies as an organization is unable to take on global efforts like: participating in strategic partnerships with other organizations or grant opportunities, developing a global PyLadies conference, etc.

In short, lacking a global structure means most of this falls onto the shoulders of a select few. These folks have been battling many challenges including burn out, lack of time, and are simply unable to keep up with global demand. If we cannot keep up with growth and evolve our model as we grow, then we are falling short of building the inclusive Python community that our mission focuses on.

**Comment by primuse** [comment]
This model works!
I like the idea of a PyLadies Conference pillar. A PyLadies Conference would be a great thing to have.

**Comment by lorenanicole** [comment]
@primuse yes! We had some attempts at doing at PyLadies Conference in the past (I legit have an entire schedule and set of docs on what to do ...) but they continue to frazzle without a clear group to own it etc.

**Comment by primuse** [comment]
I'd love to be a part of that @lorenanicole

**Comment by niharikakrishnan** [comment]
@lorenanicole I would like to be a part of the PyLadies Conference pillar too. 
A PyLadies conference would really help in letting people know about a community called PyLadies in the first place (Based on the current situation in India)!

**Comment by niharikakrishnan** [comment]
> @lorenanicole I would like to be a part of the PyLadies Conference pillar too.
> A PyLadies conference would really help in letting people know about a community called PyLadies in the first place (Based on the current situation in India)!

And if the PyLadies Conference is a future project pillar, I would like to volunteer for the Tech project pillar.

**Comment by lorenanicole** [comment]
@primuse @niharikakrishnan thanks for the support! Before we can talk about a PyLadies Conference though we need to figure out how to better support PyLadies on a global level, hence this proposal. Would you mind reviewing the proposal above and offering feedback or general thoughts (e.g. you support, don't) on the governance model? Thanks!

**Comment by mei-li** [comment]
Nice work! I wonder whether the different pillars need a bit of expansion. As I see it the resource and on boarding one has a lot of work. It looks to me the main communication pillar for all the chapters. I think maybe having a short description of main responsibilites of each to see whether it is equally distributed. 

Also I think the conference is a great idea to get the new model started and get together and feel like moving towards a common goal and exchange ideas.

I would also suggest to get members from all continents if possible in the core team to have an overview of the global situation.

I wonder whether it makes sense to have a pillar working towards diversity in conferences and other groups like pydata, pycons etc. Since the goal is women to be more active in the overall community. Even open source contibuting focused (that could be part of tech). Really I am not surr what is the tech pillar and also I have 0 experiencw with governance models

**Comment by lorenanicole** [comment]
> Nice work! I wonder whether the different pillars need a bit of expansion. 

The project pillars are meant to expand to as many projects as pyladies wants to work on. If some aren’t needed anymore those will be removed. If we need more we can add more. The size of each is also flexible and again driven by interest.

**Comment by pfctdayelise** [comment]
What is expected to concretely change as a result of adopting a governance model? I guess this is trying to fix one or more concerns, but I don't see them made explicit.

I don't love anchoring an annual meeting at PyCon US. Surely that would make more sense to be a video conference call. Or rotate location each year through Americas, Europe, Asia.

**Comment by lorenanicole** [comment]
@pfctdayelise I answered your concerns inline below:

> What is expected to concretely change as a result of adopting a governance model? I guess this is trying to fix one or more concerns, but I don't see them made explicit.

We cover this in the "Overview" category above as:

- Organizational priorities
- Resource management
- Fundraising

 However for very tangible examples:

- No one clearly owns PyLades resources like our website, the `pip install pyladies`, the blog, etc. 
- No one clearly owns creating new PyLadies chapters
- We are unable to provide direct financial support to our PyLadies chapters
- We do not have a formally established relationship with the Python Software Foundation, whom is our parent org and gives us our non-profit status
- We do not have a team to handle global Code of Conduct concerns
- We do not have clear ways to allow PyLadies members to get involved in cross cutting concerns (e.g. organizing PyLadies at PyCon USA)
- PyLadies as an organization is unable to take on global efforts like: participating in strategic partnerships with other organizations or grant opportunities, developing a global PyLadies conference, etc.
- All of this has fallen onto the shoulders of a few historical PyLadies organizers who are: burnt out, short on time, unable to keep up with global demand

In short, lacking a global structure means lots falls onto the heads of a few and we are not able to keep up with the global growth and demand for more PyLadies chapters as well as we are unable to grow and evolve our mission.

> I don't love anchoring an annual meeting at PyCon US. Surely that would make more sense to be a video conference call. Or rotate location each year through Americas, Europe, Asia.

The global team is welcome to change when they hold their annual meeting, however aiming for a max in person meeting is likely going to be a priority for this group. This issue is to focus on the model and not the particularities of *who* is in the group or *how* they are selected. Also our kick off chat at PyCon USA this year did include support for video conferencing in. 

I think this question is a bit premature but I fully agree these are the type of concerns the global body should take on to consider global diversity and inclusion of the community.

**Comment by gacafe** [comment]
- It feels like the model lacks the ability to include general PyLadies in decision making. If PyLadies up to now has been quite decentralised, having a process in which others can get involved (particularly if the leadership team is invite-only) is quite important. Since establishing such governance will yield PyLadies the ability to take a stance on things (like when things happen in the community, or when PSF decides something), it would be good to have a process which allows for people to have voice and it is not all just onto the leadership team to decide.
 
- It feels like there should be a process to ensure the leadership is in fact "global". Otherwise there is a high risk of it becoming very USA centric and as such failing to adequately account for PyLadies not in the USA and/or those who are unable to travel to the USA. This is even more relevant as the leadership team will be invite only. Maybe there can be quotas for people in the leadership team, at least, for different continents.

**Comment by mei-li** [comment]
The more I understand the idea it makes great sense! Thanks for taking the lead on this. 

With your latest comments it became more obvious what gap this governance model wants to cover, it would nice if these detailed examples were included in the proposal. (pull requests management, blogs, CoC issues)

As it looks to me the governance model aims to rather create groups that own some core topics rather than create groups that "decide for the community". If that is the case, I suggest to clarify a bit how flexible is this model and how it plans to incorporate community feedback as @gacafe mentioned. Eg.

* How it will be decided what are the pillars to work on and what is the process to be involved in one? Imho it makes sense to bootstrap some critical ones from the lead team, but also have an open space to reach the lead team suggest topics and get the community vote/willingness to participate, rather than decide on few things and implement. 

* Similarly in each pillar I think it is important that it has an open space to comment and discuss a decision or make a suggestion. Eg. Even if few people are in the Code of conduct pillar, anybody can have a suggestion or an issue that would like to discuss.

So rather than focusing on the invite only spaces in the model description, I believe it makes sense to have appointed members that own a topic and at the same time the whole discussion and decision making is as transparent and accessible from the outside as possible.

For example, I wanted to suggest that #organizers slack channel is open and not invite only. I believe there is no really need to make something restricted as normally only the "officially appointed members" or simply interested community members will participate in a topic or discussion. There is always the possibilty to switch to a private channel with few people for a topic. If openness is core part of the model, I think it has more possibilities to avoid silos or communication problems.

**Comment by drcat101** [comment]
This is really awesome! It seems like a great starting point, and I look forward to contributing to a Project Pillar.
