### ISSUE TITLE
Provide PyLadies Slack guideline (and automate this)

### ISSUE THREAD

**Issue by Mariatta** [pyladies/global-organizing#23]
It would be great if we have a general guideline for new slack members.

We can have a bot that automatically welcomes new slack members and share them some useful info like:
- welcome, what is this space about
- introduce self at #introduction
- organizers should include which chapter they organize in profile
- jobs can be posted at #jobs
- events can be posted at #events 
- find your local chapter channel
- etc

**Comment by Mariatta** [comment]
We can have the guidelines written as a doc somewhere, and just have the slackbot automaticlaly share link to the new member when they joined.

**Comment by neonejidusty** [comment]
I took sometime to design something we could use. Also, i could edit the content to suit our purpose.
![Wecome to the slack platform of the Global PyLadies Community  Kindly do well to introduce yourself, the chapter you belong to and tell us about your involvement with the Python Programming Language  Whiles](https://user-images.githubusercontent.com/29455771/68963504-f8613900-07ce-11ea-9996-1a398976303c.png)

**Comment by BethanyG** [comment]
One of the strategies that another team I am a member of (codebuddies) employs is to auto-subscribe users to specific channels when they join.  

One of those is a **'landing pad'** that gives them a specific welcome message like the excellent one @AbigailMesrenyameDogbe has posted.  

_**Maybe we can do the same?**_  Additionally, we can auto-subscribe new members to the channels mentioned in the welcome -- such as #conferences, #introductions, #general, #pyladies-support, and #africa, etc.  

Codebuddies also posts a separate "Slack Etiquette" doc for users to look over in the same "landing pad" channel.  While I think it would need re-working for our groups, I've posted it here as a potential starting place.
______________________________________
______________________________________

# The following guidelines can help you get the most from our Slack community.

.
### :star2: Every member of CodeBuddies is a _*person*_ 
 _This is a safe space. No question is "stupid.", no topic too "basic"._  
.
This community is intended for self-directed learners, CS students, programming enthusiasts, and professional developers to share knowledge and techniques. The admins, moderators, and everyone else in CodeBuddies are **donating their spare time; nobody’s being paid.**  Our suggestions/answers may not always be correct, & you may not always get an answer. Treat us like somebody friendly you don’t know who’s standing next to you offering help or suggestions.

### :star2: CodeBuddies is asynchronous & international
We have members on every continent (except Antartica), and many of us are working professionals. You may get help within 5 minutes if somebody who knows the answer is online looking for something to do -- but it’s entirely possible that you won’t get a response for an hour or day or more. If you’re asking about a less popular tool, or a specific edge case, you may even get an answer _**several days later.**_
.
So remember to keep CodeBuddies open in the background for a while after asking a question - or check back periodically.
.
Please don't cross post the same question in multiple channels. People in this community may not be super-chatty at any given moment, but we are reading posts across all channels.  Someone will eventually see (and help) you. _**We promise**_.

### :star2: Some channels are more active than others
Questions in #general or #advice tend to get answered quickly, or they get pushed off the screen & forgotten. We have a handful of dedicated people that read the scrollback and try to answer forgotten questions, but there’s a lot of discussion/movement happening, you may want to re-post after a few days.  
.
Conversely, if a channel is particularly quiet, please do not post "this channel is quiet".  Instead, try posting a question/article/or discussion point that others in the channel might comment on or enjoy.

### :star2: Don’t “ask to ask”
Newcomers very commonly ask about asking a question in one of a few ways.
.
_**“Does anyone know about [X tool or library]?”**_
The answer is probably **“yes,”** but nobody can help you until you state what your problem **is**. All too often by the time somebody asks what the **real** question is, the person who needed help has disconnected. 
.
_**Please be specific with your questions so all of us can help you even when you aren't online.**_ Share a code snippet, a link to where you're seeing the issue, a description of what is confusing you, and specifics on what you've tried so far.  More often than not, it also helps to paste your error logs into a snippet or text file (instructions here on how to do that in Slack) to accompany your question/issue.
.
_**“Is it okay if I ask about [X tool or library] here?”**_
We have a dizzying array of channels, which we’re aware of and for which we apologize. We have utility channels such as #announcements, #general, #advice, etc.  All our channels are listed alphabetically. 
.
Instead of asking, browse the Channels list for any that seem like obvious places to ask your question. If you don’t see any topics or Channels that fit, don’t hesitate to post it in #general or #advice. If there’s a better place for it, one of the moderators or other helpful users will suggest it, but don't worry - off topic messages aren’t going to get you banned.

### :star2: Don’t use `@here`, `@channel`, or ping / DM members unless it's directly relevant
It’s very tempting to try to get more attention to your question by @-mentioning one of the high profile (or recently active) members, but please don’t. They may not actually be online, they may not be able to help, and they may be in a completely different timezone–nobody likes push notifications at 3am from an impatient stranger.
.
Similarly, don’t DM other members without asking first. All of the same problems as @-mentioning apply, and private conversations can’t help anyone else. Your questions are likely not unique, and other people can learn from them when they’re asked in a public channel.

### :star2: Be helpful
We are a pay-it-forward community. If someone here has helped you, please give back by helping someone else!
.
It doesn’t matter if you can’t answer a question in a brief sentence, or if you get pulled away before you can type out further replies. If a question isn’t clear, ask a clarifying question. If you remember something you read that seemed related, send a link. A lot of people who are stuck will be fine if you can’t provide the solution, they just need another place to look.

### :star2: Be polite
All the CodeBuddies here deserve your respect, so be polite. Not “retail employee” polite......but don’t fan flamewars, get sucked into lose-lose arguments, or other internet classics.

### :star2: Be a model Slack citizen
Be the change you want to see in the world! Remember our community runs on volunteers and collaboration. If a conversation is getting heated, try to defuse it. If a hard question is unanswered, dig in & work through it with others. If a channel is full of unanswered questions, mention in #codebuddies-meta that you’d like to take ownership of it. 


### :star2::star2:Thanks to everyone who've been following these etiquette rules already!   

This community is :earth_asia: international and distributed across timezones, and it's nice to find that even with our diversity of backgrounds and experience levels and nationalities, we have similar goals and can support each other. :heart:  It's always a delight to be late-night coding – & suddenly realize that halfway around the world, a cheerful hangout collaborator is pouring their first cup of coffee for the day.

**Comment by BethanyG** [comment]
Two other thoughts:

1)  This app https://greet.bot/plans has functionality for onboarding.  it is pretty limited at the free level, but can be set to have a custom message.  Plans are 12$/mo for higher customization.

2)  We could build a slack bot of our own that interacts with new users.  Glitch has a bunch of starter code from the Slack team around doing bots with CoC and interaction, etc.  This is a like to Glitch's Slack Team Page:  https://glitch.com/@slack.  Down side is that all of the example code is JS/Node based - but there are bot frameworks in python as well.

**Comment by Mariatta** [comment]
Slack now has a custom workflow where it can greet new member who joined the channel so we can use that.

I would suggest instead of coming up with an image, we create it as a text file, either markdown or restructured text, then the bot should just provide a link to that text file. We can easily edit the text file whenever needed.

While the image is really great, I find it is less flexible when we need to make changes.

**Comment by Mariatta** [comment]
All the content that you all have come up with are great too.

**Comment by BethanyG** [comment]
Is that custom workflow for new users Slack a **paid feature**?  I'm an an admin for several Slack teams that are unpaid, and I can't seem to find where to set that up..... but that would be perfect, if we can use it.

**Comment by Mariatta** [comment]
The workflow is available on Standard, Plus, and Enterprise plans. Pyladies is under the Standard (non profit) Plan. We already have a couple Slack workflows in place, for example
![Screen Shot 2019-11-04 at 5 48 14 PM](https://user-images.githubusercontent.com/5844587/68983729-36576080-07c1-11ea-8385-cccb828d672c.png)

**Comment by BethanyG** [comment]
Perfect!  I typed up @AbigailMesrenyameDogbe  message as a `Slack Post`, so we can all work on it there.  Once it is shared in a public channel, we can also link it here.  😄

**Comment by Mariatta** [comment]
Thanks @BethanyG and @AbigailMesrenyameDogbe 
I think we can add it under /process directory of this repo:
https://github.com/pyladies/global-organizing/tree/master/process

**Comment by BethanyG** [comment]
@Mariatta @AbigailMesrenyameDogbe  -- Added two docs tohttps://github.com/pyladies/global-organizing/tree/master/process:  

1.  Slack_new_member_welcome.md - with @AbigailMesrenyameDogbe  image as  markdown.
2.  Slack_etiquette.md -- with draft "etiquette" language.

Also added a small girlgeek with workmark image for use as logo in the welcome msg.

**Comment by lorenanicole** [comment]
This work has been merged in per: https://github.com/pyladies/global-organizing/pull/44 and now closing the issue.
